/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cronometro;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author nel_g
 */
public class FrmCronometro extends javax.swing.JFrame {

    /**
     * Creates new form FrmCronometro
     */
    int contador,msegundo,segundo,minuto,puntaje1,puntaje2;
    
    Timer temporizador = new Timer ( 100,new ActionListener()
    {
       public void actionPerformed ( ActionEvent e )
        {
            lblmsegundo.setText(":" + "  " + String.valueOf(msegundo));
            lblsegundo.setText(":" + "  " + String.valueOf(segundo));
            lblminuto.setText( String.valueOf( minuto ) );
            
            if( msegundo > 9)
            {
                msegundo = 0;
                segundo += 1;
                if (segundo > 59)
                {
                    segundo = 0;
                    minuto += 1;
                }
            }
            contador +=1;
            msegundo+=1;
        } 
    });
    
    
    public FrmCronometro() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnIniciar = new javax.swing.JButton();
        BtnParar = new javax.swing.JButton();
        BtnReiniciar = new javax.swing.JButton();
        lblminuto = new javax.swing.JLabel();
        lblsegundo = new javax.swing.JLabel();
        lblmsegundo = new javax.swing.JLabel();
        lblpunto = new javax.swing.JLabel();
        lblpunto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnIniciar.setText("Iniciar");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        BtnParar.setText("Parar");
        BtnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPararActionPerformed(evt);
            }
        });

        BtnReiniciar.setText("Reiniciar");
        BtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReiniciarActionPerformed(evt);
            }
        });

        lblminuto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblsegundo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblmsegundo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblpunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblpunto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblminuto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmsegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpunto2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpunto2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblminuto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnParar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnReiniciar))
                    .addComponent(lblsegundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmsegundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        // TODO add your handling code here:
        lblmsegundo.setText(":" + "  " + String.valueOf(msegundo));
        lblsegundo.setText(":" + "  " + String.valueOf(segundo));
        lblminuto.setText( String.valueOf( minuto ) );
        lblpunto.setText( String.valueOf( puntaje1 ) );
        lblpunto2.setText( String.valueOf( puntaje2 ) );
        temporizador.start();
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void BtnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPararActionPerformed
        // TODO add your handling code here:
        temporizador.stop();
        if( msegundo == 1)
        {
            puntaje1 += 1;
            lblpunto.setText( String.valueOf( puntaje1 ) );
        }
        else
        {
            puntaje2 += 1;
            lblpunto2.setText( String.valueOf( puntaje2 ) );
        }
    }//GEN-LAST:event_BtnPararActionPerformed

    private void BtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReiniciarActionPerformed
        // TODO add your handling code here:
        contador = 0;
        msegundo = 0;
        segundo = 0; 
        minuto = 0;
        puntaje1 = 0;
        puntaje2 = 0;
        lblmsegundo.setText(":" + "  " + String.valueOf(msegundo));
        lblsegundo.setText(":" + "  " + String.valueOf(segundo));
        lblminuto.setText( String.valueOf( minuto ) );
        lblpunto.setText( String.valueOf( puntaje1 ) );
        lblpunto2.setText( String.valueOf( puntaje2 ) );
        temporizador.stop();
    }//GEN-LAST:event_BtnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JButton BtnParar;
    private javax.swing.JButton BtnReiniciar;
    private javax.swing.JLabel lblminuto;
    private javax.swing.JLabel lblmsegundo;
    private javax.swing.JLabel lblpunto;
    private javax.swing.JLabel lblpunto2;
    private javax.swing.JLabel lblsegundo;
    // End of variables declaration//GEN-END:variables
}
